### ISSUE TITLE
Build Project Problem

### ISSUE THREAD

**Issue by sdfiske** [alien4cloud/alien4cloud#134]
Hello,

Build problem experienced on Windows 10. This is exactly the same build problem reported in issue 130 by jwlai on April 25, 2018.  The issue 130 comments were very useful but did not actually solve the underlying build problem on my computer. 

On Windows 10, I installed JDK 8 V172, Maven 3.5.3, Ruby 2.4.4.1, Python 3.6.5, NodeJS 8.11.1, Git 2.17.0, Spring Tool Suite 3.9.4 as well as bower, grunt-cli, compass, grunt-contrib-compass

Executed suggestion from issue 102 in https://github.com/Hacklone/private-bower/issues/102:

git config --global url."https://".insteadOf git://

Project build command executed:

mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

Error encountered:

. . . . . . . 
. . . . . . . 
. . . . . . .
Running "rev:appFiles" (rev) task
target/webapp/scripts/alien4cloud-dependencies.js >> 70ed20c4.alien4cloud-dependencies.js
target/webapp/scripts/alien4cloud-bootstrap.js >> de0df333.alien4cloud-bootstrap.js
target/webapp/styles/main.css >> b9269447.main.css
target/webapp/views/alien4cloud-templates.js >> 95aef1e1.alien4cloud-templates.js
target/webapp/data/languages/locale-en-us.json >> 42b0e931.locale-en-us.json
target/webapp/data/languages/locale-fr-fr.json >> dc884ccf.locale-fr-fr.json
target/webapp/data/languages/locale-ja-jp.json >> f0b67c0c.locale-ja-jp.json
target/webapp/data/languages/locale-zh-cn.json >> 708b85c6.locale-zh-cn.json

Running "execute:revrename" (execute) task
-> module call undefined
C:\alien4cloud-develop\alien4cloud-ui\node_modules\tmp\lib\tmp.js:261
  throw err;
  ^

TypeError: cb is not a function
    at CB (C:\alien4cloud-develop\alien4cloud-ui\node_modules\bower\node_modules\graceful-fs\graceful-fs.js:275:7)
    at FSReqWrap.oncomplete (fs.js:135:15)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Application LIfecycle ENabler parent project. 2.1.0-SNAPSHOT SUCCESS [  1.890 s]
[INFO] Alien 4 Cloud Common ............................... SUCCESS [ 22.601 s]
[INFO] Alien 4 Cloud TOSCA ................................ SUCCESS [ 43.275 s]
[INFO] Alien 4 Cloud Dao .................................. SUCCESS [  8.550 s]
[INFO] Alien 4 Cloud Security ............................. SUCCESS [ 17.140 s]
[INFO] Alien 4 Cloud Test Common .......................... SUCCESS [  7.750 s]
[INFO] Alien 4 Cloud Core ................................. SUCCESS [01:21 min]
[INFO] Alien 4 Cloud Mock PaaS provider ................... SUCCESS [ 16.460 s]
[INFO] Alien 4 Cloud rest API ............................. SUCCESS [ 31.460 s]
[INFO] Alien 4 Cloud REST Integration Test ................ SUCCESS [ 21.016 s]
[INFO] Alien 4 Cloud UI 2.1.0-SNAPSHOT .................... FAILURE [02:57 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:08 min
[INFO] Finished at: 2018-05-04T11:53:25-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal fr.fastconnect:calm-yeoman-maven-plugin:1.0.3:package (default) on project alien4cloud-ui: Error during : cmd /c grunt build --no-color: Process exited with an error: 7 (Exit value: 7) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alien4cloud-ui

c:\alien4cloud-develop>

Any help or suggestions would be greatly appreciated.

Thanks, Steve

**Comment by EdgarLGB** [comment]
Hi @sdfiske , I recommend you to install all the prerequisites found [here](https://alien4cloud.github.io/#/developer_guide/index.html) for building Alien4Cloud.

**Comment by sdfiske** [comment]
Hello Philippe and Edgar,

I previously installed the prerequisites using documentation at https://github.com/alien4cloud/alien4cloud instead of https://alien4cloud.github.io/#/developer_guide/index.html.

I noticed that https://alien4cloud.github.io/#/developer_guide/index.html indicates team is using Maven v3.0.5 and Node.js version 4.8.0 that includes npm 2.7.4.

I installed latest Maven 3.5.3 and Node.js 8.11.1 which includes npm 5.6.0 from Internet.

***Should I try reinstalling Maven 3.0.5 (February 23, 2013 release) instead of Maven 3.5.3? 

https://nodejs.org/en/download/releases/ indicates that Node.js v4.8.0 includes npm 2.15.11 not npm 2.7.4.  

https://nodejs.org/en/download/releases/ indicates that io.js 1.6.3 (March 31, 2015 before renamed to Node.js) includes npm 2.7.4.

***Should I reinstall different version of Node.js or io.js  instead of Node.js 8.11.1/npm 5.6.0 that I installed?

***Should I install Node.js v4.8.0/npm 2.15.11 or io.js 1.6.3/npm 2.7.4 or something else?

Thank you very much for your help!

Thanks, Steve

**Comment by OresteVisari** [comment]
You have a Javascript error, so test to downgrade your Nodejs version (and
use the version specify in requirements).

**Comment by sdfiske** [comment]
Installed Node.js v4.8.0 and Maven v3.0.5 and same build error occurs.

Node.js v4.8.0 is packaged with npm 2.15.11 on https://nodejs.org/

c:\alien4cloud-develop>node -v
v4.8.0

c:\alien4cloud-develop>npm -v
2.15.11

c:\alien4cloud-develop>where mvn
C:\apache-maven-3.0.5\bin\mvn
C:\apache-maven-3.0.5\bin\mvn.bat

c:\alien4cloud-develop>mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
. . . . .
. . . . .
. . . . .
Running "rev:appFiles" (rev) task
target/webapp/scripts/alien4cloud-dependencies.js >> c6a93249.alien4cloud-dependencies.js
target/webapp/scripts/alien4cloud-bootstrap.js >> bb3feb9f.alien4cloud-bootstrap.js
target/webapp/styles/main.css >> ce65602b.main.css
target/webapp/views/alien4cloud-templates.js >> abf551a0.alien4cloud-templates.js
target/webapp/data/languages/locale-en-us.json >> f6a2df3c.locale-en-us.json
target/webapp/data/languages/locale-fr-fr.json >> 0841806b.locale-fr-fr.json
target/webapp/data/languages/locale-ja-jp.json >> 9d5d20ca.locale-ja-jp.json
target/webapp/data/languages/locale-zh-cn.json >> f22b67ac.locale-zh-cn.json

Running "execute:revrename" (execute) task
-> module call <anonymous>
C:\alien4cloud-develop\alien4cloud-ui\node_modules\tmp\lib\tmp.js:261
  throw err;
  ^

TypeError: cb is not a function
    at CB (C:\alien4cloud-develop\alien4cloud-ui\node_modules\bower\node_modules\graceful-fs\graceful-fs.js:275:7)
    at FSReqWrap.oncomplete (fs.js:82:15)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Application LIfecycle ENabler parent project. ..... SUCCESS [1.312s]
[INFO] Alien 4 Cloud Common .............................. SUCCESS [21.092s]
[INFO] Alien 4 Cloud TOSCA ............................... SUCCESS [36.943s]
[INFO] Alien 4 Cloud Dao ................................. SUCCESS [7.536s]
[INFO] Alien 4 Cloud Security ............................ SUCCESS [16.714s]
[INFO] Alien 4 Cloud Test Common ......................... SUCCESS [6.937s]
[INFO] Alien 4 Cloud Core ................................ SUCCESS [1:08.075s]
[INFO] Alien 4 Cloud Mock PaaS provider .................. SUCCESS [16.410s]
[INFO] Alien 4 Cloud rest API ............................ SUCCESS [28.853s]
[INFO] Alien 4 Cloud REST Integration Test ............... SUCCESS [20.265s]
[INFO] Alien 4 Cloud UI .................................. FAILURE [1:57.814s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:42.295s
[INFO] Finished at: Mon May 07 16:03:15 PDT 2018
[INFO] Final Memory: 249M/1409M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal fr.fastconnect:calm-yeoman-maven-plugin:1.0.3:package (default) on project alien4cloud-ui: Error during : cmd /c grunt build --no-color: Process exited with an error: 7 (Exit value: 7) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alien4cloud-ui
c:\alien4cloud-develop>

**Comment by swqmaven** [comment]
I get the same error! it looks like the angular-translate#2.14.0 doesn't match。
do it and resolve:

`
cd C:\xxxxxx\alien4cloud\alien4cloud-ui>bower install angular-translate
......
Unable to find a suitable version for angular-translate, please choose one by typing one of the numbers below:
    1) angular-translate#~2.13.1 which resolved to 2.13.1 and is required by angular-translate-loader-static-files#2.13.1
    2) angular-translate#~2.14.0 which resolved to 2.14.0 and is required by angular-translate-loader-static-files#2.14.0, angular-translate-storage-cookie#2.14.0
    3) angular-translate#2.14.0 which resolved to 2.14.0 and is required by alien4cloud
    4) angular-translate#^2.18.1 which resolved to 2.18.1
Prefix the choice with ! to persist it to bower.json

? Answer 3
bower angular-translate-storage-cookie#2.14.0          install angular-translate-storage-cookie#2.14.0
bower angular-translate#2.14.0                         install angular-translate#2.14.0
bower angular-translate-loader-static-files#2.14.0     install angular-translate-loader-static-files#2.14.0
`

**Comment by SellamiRami** [comment]
Hello, 
I am trying to build the project on Eclipse and I have the same issue with npm.

Could you please help me in fixing this error.

Please find below the error message: 

` ---------------------< alien4cloud:alien4cloud-ui >---------------------
[INFO] Building Alien 4 Cloud UI 2.2.0-SNAPSHOT                         [11/11]
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- calm-yeoman-maven-plugin:1.0.3:init (default) @ alien4cloud-ui ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Application LIfecycle ENabler parent project. 2.2.0-SNAPSHOT SUCCESS [  1.066 s]
[INFO] Alien 4 Cloud Common ............................... SUCCESS [  8.108 s]
[INFO] Alien 4 Cloud TOSCA ................................ SUCCESS [ 13.232 s]
[INFO] Alien 4 Cloud Dao .................................. SUCCESS [  3.504 s]
[INFO] Alien 4 Cloud Security ............................. SUCCESS [  5.581 s]
[INFO] Alien 4 Cloud Test Common .......................... SUCCESS [  1.085 s]
[INFO] Alien 4 Cloud Core ................................. SUCCESS [ 23.419 s]
[INFO] Alien 4 Cloud Mock PaaS provider ................... SUCCESS [  6.002 s]
[INFO] Alien 4 Cloud rest API ............................. SUCCESS [ 10.024 s]
[INFO] Alien 4 Cloud REST Integration Test ................ SUCCESS [  8.920 s]
[INFO] Alien 4 Cloud UI 2.2.0-SNAPSHOT .................... FAILURE [  0.109 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2019-05-14T14:30:29+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal fr.fastconnect:calm-yeoman-maven-plugin:1.0.3:init (default) on project alien4cloud-ui: Error during : npm install: Cannot run program "npm" (in directory "/Users/rs/CETIC/Asset/alien4cloud-develop/alien4cloud-ui"): error=2, No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :alien4cloud-ui
`

Thank you in advance. 
Rami.

**Comment by adispataru** [comment]
I see this issue is still open and I recently encountered similar output with @sdfiske and @SellamiRami, but on macOS using nodejs v10.10. In my case the error was more obvious: 
```
Running "execute:revrename" (execute) task
-> module call undefined
/Users/adrian/Documents/aspide/origa4c/alien4cloud/alien4cloud-ui/node_modules/tmp/lib/tmp.js:261
  throw err;
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.rename (fs.js:571:14)
    at /Users/adrian/Documents/aspide/origa4c/alien4cloud/alien4cloud-ui/src/main/build/config/execute.js:104:20
    at Array.forEach (<anonymous>)
    at /Users/adrian/Documents/aspide/origa4c/alien4cloud/alien4cloud-ui/src/main/build/config/execute.js:101:21
    at FSReqWrap.oncomplete (fs.js:141:20)
```
localizing the problem I was able to reach [this](https://github.com/elmsln/wcfactory/issues/148) issue which involves a deprecated use of `rename`, which should be replaced with `renameSync` in `alien4cloud-ui/src/main/build/config/execute.js`, line 104. 

I have solved this issue in my [private fork](https://github.com/adispataru/alien4cloud/commit/1c36b0c4b49abcde9d433833f44aee7f73ed1220) and I can make a pull request to the devel branch if this does not conflict with other dependencies.
