### ISSUE TITLE
UNKNOWN_TOSCA_VERSION

### ISSUE THREAD

**Issue by SellamiRami** [alien4cloud/alien4cloud#177]
Hello, 
I am trying to use the TOSCA parser. To do so, I created the following main class in the alien4cloud.tosca.main package: 

`
    package alien4cloud.tosca.main;

    import java.nio.file.Paths;
    import alien4cloud.tosca.model.ArchiveRoot;
    import alien4cloud.tosca.parser.ParsingException;
    import alien4cloud.tosca.parser.ParsingResult;
    import alien4cloud.tosca.parser.ToscaParser;

    public class main {
        static String getRootDirectory() {
            return "/Users/rs/TOSCA-EXAMPLES/EXAMPLES/1-Compute/";
        }
        public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
		    ToscaParser tp = new ToscaParser();
		    ParsingResult<ArchiveRoot> pr = tp.parseFile(Paths.get(getRootDirectory(), "Compute-TOSCA.yaml"));
		} catch (ParsingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}}}

The TOSCA file is the following:
`
tosca_definitions_version: tosca_simple_yaml_1_0
description: TOSCA simple profile 
topology_template: 
  inputs: 
    cpus: 
      type: integer
      description: Number of CPUs for the server.
      constraints: 
        - valid_values:  [ 1, 2, 4, 8 ]
  node_templates: 
    my_server: 
      type: tosca.nodes.Compute
      capabilities: 
        host: 
          properties: 
            disk_size: 10 GB
            mem_size: 1 GB
            num_cpus: 
              get_input: cpus
        os: 
          properties: 
            architecture: x86_64
            distribution: ubuntu
            type: Linux
            version: 12.04
`

When I  run the main class, I get the following error: 

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
alien4cloud.tosca.parser.ParsingException: ParsingError(errorLevel=ERROR, errorCode=UNKNOWN_TOSCA_VERSION, context=Definition version is not supported, startMark=SimpleMark(line=1, column=1), problem=Version is not supported by Alien4Cloud, endMark=SimpleMark(line=1, column=28), note=tosca_simple_yaml_1_0)
	at alien4cloud.tosca.parser.ToscaParser.getParser(ToscaParser.java:116)
	at alien4cloud.tosca.parser.YamlParser.doParsing(YamlParser.java:110)
	at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:93)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:84)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:31)
	at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:55)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:96)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:31)
	at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:39)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:90)
	at alien4cloud.tosca.main.main.main(main.java:18)
`
Could you please help in fixing this error?

Thank you in advance for your response and help.

Best regards, 
Rami Sellami.

**Comment by loicalbertin** [comment]
Hi @SellamiRami 

Sorry for the delay did you try to change `tosca_definitions_version: tosca_simple_yaml_1_0` to `tosca_definitions_version: alien_dsl_2_0_0`?

I think that you DSL version is not recognized by the parser.
Maybe @xdegenne or @SebastienLaurent  can confirm?

**Comment by SellamiRami** [comment]
Dear @loicalbertin,
Thank you for your reply. In fact, I have already tested all the versions supported by A4C before posting the issue.

I tried your suggestion and I replaced the current version with "alien_dsl_2_0_0" and I get the same error : 

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
alien4cloud.tosca.parser.ParsingException: ParsingError(errorLevel=ERROR, errorCode=UNKNOWN_TOSCA_VERSION, context=Definition version is not supported, startMark=SimpleMark(line=1, column=1), problem=Version is not supported by Alien4Cloud, endMark=SimpleMark(line=1, column=28), note=alien_dsl_2_0_0)
	at alien4cloud.tosca.parser.ToscaParser.getParser(ToscaParser.java:116)
	at alien4cloud.tosca.parser.YamlParser.doParsing(YamlParser.java:110)
	at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:93)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:84)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:31)
	at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:55)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:96)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:31)
	at alien4cloud.tosca.parser.YamlParser.parseFile(YamlParser.java:39)
	at alien4cloud.tosca.parser.ToscaParser.parseFile(ToscaParser.java:90)
	at alien4cloud.tosca.main.Main.main(Main.java:17)
`

**Comment by ramu-n** [comment]
Hi,
have you resolved the issue ? if not first resolve the SLF4J problem in your environment.. 
i suspect parser initialisation is failed.
