### ISSUE TITLE
Issue building the `develop` branch

### ISSUE THREAD

**Issue by andreaturli** [alien4cloud/alien4cloud#62]
Using 
`$ mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -X`

I get this error back

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Application LIfecycle ENabler parent project. ...... SUCCESS [  0.209 s]
[INFO] Alien 4 Cloud Common ............................... SUCCESS [  3.470 s]
[INFO] Alien 4 Cloud Security ............................. SUCCESS [  3.330 s]
[INFO] Alien 4 Cloud Core ................................. SUCCESS [ 10.318 s]
[INFO] Alien 4 Cloud Mock PaaS provider ................... SUCCESS [  2.542 s]
[INFO] Alien 4 Cloud rest API ............................. SUCCESS [  4.694 s]
[INFO] Alien 4 Cloud Compilation Tool ..................... SUCCESS [  4.160 s]
[INFO] Alien 4 Cloud REST Integration Test ................ SUCCESS [ 13.557 s]
[INFO] Alien 4 Cloud UI ................................... FAILURE [  6.781 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.632 s
[INFO] Finished at: 2015-06-03T11:15:51+02:00
[INFO] Final Memory: 36M/820M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal fr.fastconnect:calm-yeoman-maven-plugin:1.0.3:package (default) on project alien4cloud-ui: Error during : grunt build --no-color: Process exited with an error: 6 (Exit value: 6) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal fr.fastconnect:calm-yeoman-maven-plugin:1.0.3:package (default) on project alien4cloud-ui: Error during : grunt build --no-color
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during : grunt build --no-color
	at fr.fastconnect.ExecuteCommandUtil.executeCommand(ExecuteCommandUtil.java:37)
	at fr.fastconnect.YeomanPackageMojo.execute(YeomanPackageMojo.java:23)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 6 (Exit value: 6)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at fr.fastconnect.ExecuteCommandUtil.executeCommand(ExecuteCommandUtil.java:35)
	... 22 more

Any suggestions?

**Comment by lucboutier** [comment]
Sorry I didn't saw your message...
The error is probably before this stack, here you have the maven stack but it says that the error is during the grunt processing "Error during : grunt"

I guess that you have messages before the maven Reactor Summary.

**Comment by andreaturli** [comment]
Not a problem @lucboutier !

You are right, I could see a message like
```
Running "concurrent:dist" (concurrent) task
    Warning: >> Local Npm module "grunt-protractor_webdriver" not found. Is it installed?

    Running "compass:dist" (compass) task
    Warning: You need to have Ruby and Compass installed and in your system PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-compass Use --force to continue.

    Aborted due to warnings.
```

Googling a bit (not familiar with grunt and angularjs) I found a similar [issue](https://github.com/gruntjs/grunt-contrib-compass/issues/66#issuecomment-26468504): ruby is installed but compass was not there even if I installed it as suggested `gem install compass`

In my case `sudo gem install compass` seems to solve the issue, maybe a new README version could help other folks.

Thanks

**Comment by lucboutier** [comment]
We already had these steps in the readme ;)

install compass
$ gem install compass
and grunt-contrib-compass
$ npm install grunt-contrib-compass --save-dev

**Comment by andreaturli** [comment]
Correct, but I needed to use `sudo gem install compass` otherwise it was not working for me.
